# https://taskfile.dev

version: "3"

interval: 200ms

tasks:
  tools:
    cmds:
      - go install github.com/valyala/quicktemplate/qtc@latest
    sources:
      - echo `which qtc`

  gen:
    sources:
      - "**/*.go"
      - "**/*.*tmpl"
    cmds:
      - go run cmd/gen/*.go

  test:
    deps:
      - gen
    sources:
      - "**/*.go"
    cmds:
      - go test ./...

  default:
    deps:
      - test
    silent: true
