# https://taskfile.dev

version: "3"

vars:
  VERSION: 0.3.0

interval: 1000ms

tasks:
  gen:
    sources:
      - "generator/**/*"
      - "examples/**/*"
      - "cmd/**/*"
    generates:
      - "html/**/*.go"
    cmds:
      - go run cmd/gen/*.go
      - go fmt ./...

  test:
    deps:
      - gen
    cmds:
      - go test ./...

  libpub:
    dir: ./library
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push origin --tags
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/delaneyj/gostar@v{{.VERSION}}

  default:
    deps:
      - test
    silent: true
