// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package svg feMergeNode is generated from configuration file.
// Description:
package elements

import (
	"fmt"
	"html"
	"time"

	"github.com/goccy/go-json"
	"github.com/igrmk/treemap/v2"
	"github.com/samber/lo"
)

// The <feMergeNode> SVG element allows a series of filter primitives to be
// connected together graphically
// Incoming nodes are blended into the background via the defined compositing
// operator.
type SVGFEMERGENODEElement struct {
	*Element
}

// Create a new SVGFEMERGENODEElement element.
// This will create a new element with the tag
// "feMergeNode" during rendering.
func SVG_FEMERGENODE(children ...ElementRenderer) *SVGFEMERGENODEElement {
	e := NewElement("feMergeNode", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEMERGENODEElement{Element: e}
}

func (e *SVGFEMERGENODEElement) Children(children ...ElementRenderer) *SVGFEMERGENODEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEMERGENODEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEMERGENODEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEMERGENODEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEMERGENODEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEMERGENODEElement) Attr(name string, value string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEMERGENODEElement) Attrs(attrs ...string) *SVGFEMERGENODEElement {
	if len(attrs)%2 != 0 {
		panic("attrs must be a multiple of 2")
	}
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for i := 0; i < len(attrs); i += 2 {
		k := attrs[i]
		v := attrs[i+1]
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGFEMERGENODEElement) AttrsMap(attrs map[string]string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for k, v := range attrs {
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGFEMERGENODEElement) Text(text string) *SVGFEMERGENODEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEMERGENODEElement) TextF(format string, args ...any) *SVGFEMERGENODEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGENODEElement) IfText(condition bool, text string) *SVGFEMERGENODEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEMERGENODEElement) IfTextF(condition bool, format string, args ...any) *SVGFEMERGENODEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEMERGENODEElement) Escaped(text string) *SVGFEMERGENODEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEMERGENODEElement) IfEscaped(condition bool, text string) *SVGFEMERGENODEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEMERGENODEElement) EscapedF(format string, args ...any) *SVGFEMERGENODEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGENODEElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEMERGENODEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEMERGENODEElement) CustomData(key, value string) *SVGFEMERGENODEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEMERGENODEElement) IfCustomData(condition bool, key, value string) *SVGFEMERGENODEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEMERGENODEElement) CustomDataF(key, format string, args ...any) *SVGFEMERGENODEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGENODEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEMERGENODEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEMERGENODEElement) CustomDataRemove(key string) *SVGFEMERGENODEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The identifier for the input SVGAnimatedString attribute on the given
// 'feMergeNode' element.
func (e *SVGFEMERGENODEElement) IN(s string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in", s)
	return e
}

func (e *SVGFEMERGENODEElement) INF(format string, args ...any) *SVGFEMERGENODEElement {
	return e.IN(fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGENODEElement) IfIN(condition bool, s string) *SVGFEMERGENODEElement {
	if condition {
		e.IN(s)
	}
	return e
}

func (e *SVGFEMERGENODEElement) IfINF(condition bool, format string, args ...any) *SVGFEMERGENODEElement {
	if condition {
		e.IN(fmt.Sprintf(format, args...))
	}
	return e
}

// Remove the attribute IN from the element.
func (e *SVGFEMERGENODEElement) INRemove(s string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in")
	return e
}

func (e *SVGFEMERGENODEElement) INRemoveF(format string, args ...any) *SVGFEMERGENODEElement {
	return e.INRemove(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEMERGENODEElement) ID(s string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

func (e *SVGFEMERGENODEElement) IDF(format string, args ...any) *SVGFEMERGENODEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGENODEElement) IfID(condition bool, s string) *SVGFEMERGENODEElement {
	if condition {
		e.ID(s)
	}
	return e
}

func (e *SVGFEMERGENODEElement) IfIDF(condition bool, format string, args ...any) *SVGFEMERGENODEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Remove the attribute ID from the element.
func (e *SVGFEMERGENODEElement) IDRemove(s string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

func (e *SVGFEMERGENODEElement) IDRemoveF(format string, args ...any) *SVGFEMERGENODEElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEMERGENODEElement) CLASS(s ...string) *SVGFEMERGENODEElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

func (e *SVGFEMERGENODEElement) IfCLASS(condition bool, s ...string) *SVGFEMERGENODEElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Remove the attribute CLASS from the element.
func (e *SVGFEMERGENODEElement) CLASSRemove(s ...string) *SVGFEMERGENODEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEMERGENODEElement) STYLEF(k string, format string, args ...any) *SVGFEMERGENODEElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGENODEElement) IfSTYLE(condition bool, k string, v string) *SVGFEMERGENODEElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

func (e *SVGFEMERGENODEElement) STYLE(k string, v string) *SVGFEMERGENODEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

func (e *SVGFEMERGENODEElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGFEMERGENODEElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Add the attributes in the map to the element.
func (e *SVGFEMERGENODEElement) STYLEMap(m map[string]string) *SVGFEMERGENODEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Add pairs of attributes to the element.
func (e *SVGFEMERGENODEElement) STYLEPairs(pairs ...string) *SVGFEMERGENODEElement {
	if len(pairs)%2 != 0 {
		panic("Must have an even number of pairs")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}

	for i := 0; i < len(pairs); i += 2 {
		kv.Add(pairs[i], pairs[i+1])
	}

	return e
}

func (e *SVGFEMERGENODEElement) IfSTYLEPairs(condition bool, pairs ...string) *SVGFEMERGENODEElement {
	if condition {
		e.STYLEPairs(pairs...)
	}
	return e
}

// Remove the attribute STYLE from the element.
func (e *SVGFEMERGENODEElement) STYLERemove(keys ...string) *SVGFEMERGENODEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}

// Merges the singleton store with the given object

func (e *SVGFEMERGENODEElement) DATASTAR_STORE(v any) *SVGFEMERGENODEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	e.CustomDataAttributes.Set("store", html.EscapeString(string(b)))
	return e
}

// Sets the reference of the element

func (e *SVGFEMERGENODEElement) DATASTAR_REF(expression string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-ref"

	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_REF(condition bool, expression string) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_REF(expression)
	}
	return e
}

// Remove the attribute DATASTAR_REF from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_REFRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-ref")
	return e
}

// Sets the value of the element

func (e *SVGFEMERGENODEElement) DATASTAR_BIND(key string, expression string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key = fmt.Sprintf("data-bind-%s", key)

	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_BIND(condition bool, key string, expression string) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_BIND(key, expression)
	}
	return e
}

// Remove the attribute DATASTAR_BIND from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_BINDRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-bind")
	return e
}

// Sets the value of the element

func (e *SVGFEMERGENODEElement) DATASTAR_MODEL(expression string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-model"

	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_MODEL(condition bool, expression string) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_MODEL(expression)
	}
	return e
}

// Remove the attribute DATASTAR_MODEL from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_MODELRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-model")
	return e
}

// Sets the textContent of the element

func (e *SVGFEMERGENODEElement) DATASTAR_TEXT(expression string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-text"

	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_TEXT(condition bool, expression string) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_TEXT(expression)
	}
	return e
}

// Remove the attribute DATASTAR_TEXT from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_TEXTRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-text")
	return e
}

// Sets the event handler of the element

type SVGFeMergeNodeOnMod customDataKeyModifier

// Debounces the event handler
func SVGFeMergeNodeOnModDebounce(
	d time.Duration,
) SVGFeMergeNodeOnMod {
	return func() string {
		return fmt.Sprintf("debounce_%dms", d.Milliseconds())
	}
}

// Throttles the event handler
func SVGFeMergeNodeOnModThrottle(
	d time.Duration,
) SVGFeMergeNodeOnMod {
	return func() string {
		return fmt.Sprintf("throttle_%dms", d.Milliseconds())
	}
}

func (e *SVGFEMERGENODEElement) DATASTAR_ON(key string, expression string, modifiers ...SVGFeMergeNodeOnMod) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key = fmt.Sprintf("data-on-%s", key)

	customMods := lo.Map(modifiers, func(m SVGFeMergeNodeOnMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_ON(condition bool, key string, expression string, modifiers ...SVGFeMergeNodeOnMod) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_ON(key, expression, modifiers...)
	}
	return e
}

// Remove the attribute DATASTAR_ON from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_ONRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-on")
	return e
}

// Sets the focus of the element

func (e *SVGFEMERGENODEElement) DATASTAR_FOCUSSet(b bool) *SVGFEMERGENODEElement {
	key := "data-focus"
	e.BoolAttributes.Set(key, b)
	return e
}

func (e *SVGFEMERGENODEElement) DATASTAR_FOCUS() *SVGFEMERGENODEElement {
	return e.DATASTAR_FOCUSSet(true)
}

// Sets the header of for fetch requests

func (e *SVGFEMERGENODEElement) DATASTAR_HEADER(key string, expression string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key = fmt.Sprintf("data-header-%s", key)

	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_HEADER(condition bool, key string, expression string) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_HEADER(key, expression)
	}
	return e
}

// Remove the attribute DATASTAR_HEADER from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_HEADERRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-header")
	return e
}

// Sets the indicator selector for fetch requests

func (e *SVGFEMERGENODEElement) DATASTAR_FETCH_INDICATOR(expression string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-fetch-indicator"

	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_FETCH_INDICATOR(condition bool, expression string) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_FETCH_INDICATOR(expression)
	}
	return e
}

// Remove the attribute DATASTAR_FETCH_INDICATOR from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_FETCH_INDICATORRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-fetch-indicator")
	return e
}

// Sets the visibility of the element

func (e *SVGFEMERGENODEElement) DATASTAR_SHOWSet(b bool) *SVGFEMERGENODEElement {
	key := "data-show"
	e.BoolAttributes.Set(key, b)
	return e
}

func (e *SVGFEMERGENODEElement) DATASTAR_SHOW() *SVGFEMERGENODEElement {
	return e.DATASTAR_SHOWSet(true)
}

// Triggers the callback when the element intersects the viewport

func (e *SVGFEMERGENODEElement) DATASTAR_INTERSECTS(expression string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-intersects"

	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_INTERSECTS(condition bool, expression string) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_INTERSECTS(expression)
	}
	return e
}

// Remove the attribute DATASTAR_INTERSECTS from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_INTERSECTSRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-intersects")
	return e
}

// Teleports the element to the given selector

func (e *SVGFEMERGENODEElement) DATASTAR_TELEPORTSet(b bool) *SVGFEMERGENODEElement {
	key := "data-teleport"
	e.BoolAttributes.Set(key, b)
	return e
}

func (e *SVGFEMERGENODEElement) DATASTAR_TELEPORT() *SVGFEMERGENODEElement {
	return e.DATASTAR_TELEPORTSet(true)
}

// Scrolls the element into view

func (e *SVGFEMERGENODEElement) DATASTAR_SCROLL_INTO_VIEWSet(b bool) *SVGFEMERGENODEElement {
	key := "data-scroll-into-view"
	e.BoolAttributes.Set(key, b)
	return e
}

func (e *SVGFEMERGENODEElement) DATASTAR_SCROLL_INTO_VIEW() *SVGFEMERGENODEElement {
	return e.DATASTAR_SCROLL_INTO_VIEWSet(true)
}

// Setup the ViewTransitionAPI for the element

func (e *SVGFEMERGENODEElement) DATASTAR_VIEW_TRANSITION(expression string) *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-view-transition"

	e.StringAttributes.Set(key, expression)
	return e
}

func (e *SVGFEMERGENODEElement) IfDATASTAR_VIEW_TRANSITION(condition bool, expression string) *SVGFEMERGENODEElement {
	if condition {
		e.DATASTAR_VIEW_TRANSITION(expression)
	}
	return e
}

// Remove the attribute DATASTAR_VIEW_TRANSITION from the element.
func (e *SVGFEMERGENODEElement) DATASTAR_VIEW_TRANSITIONRemove() *SVGFEMERGENODEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("data-view-transition")
	return e
}
