// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package svg use is generated from configuration file.
// Description:
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <use> SVG element includes a reference to a <symbol> element and attempts
// to display the referenced content
// The reference is drawn exactly as it was defined
// It can be reused as often as needed and can be programmatically manipulated.
type SVGUSEElement struct {
	*Element
}

// Create a new SVGUSEElement element.
// This will create a new element with the tag
// "use" during rendering.
func SVG_USE(children ...ElementRenderer) *SVGUSEElement {
	e := NewElement("use", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGUSEElement{Element: e}
}

func (e *SVGUSEElement) Children(children ...ElementRenderer) *SVGUSEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGUSEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGUSEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGUSEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGUSEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGUSEElement) Text(text string) *SVGUSEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGUSEElement) TextF(format string, args ...any) *SVGUSEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGUSEElement) IfText(condition bool, text string) *SVGUSEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGUSEElement) IfTextF(condition bool, format string, args ...any) *SVGUSEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGUSEElement) Escaped(text string) *SVGUSEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGUSEElement) IfEscaped(condition bool, text string) *SVGUSEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGUSEElement) EscapedF(format string, args ...any) *SVGUSEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGUSEElement) IfEscapedF(condition bool, format string, args ...any) *SVGUSEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGUSEElement) CustomData(key, value string) *SVGUSEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGUSEElement) IfCustomData(condition bool, key, value string) *SVGUSEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGUSEElement) CustomDataF(key, format string, args ...any) *SVGUSEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGUSEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGUSEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGUSEElement) CustomDataRemove(key string) *SVGUSEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// A URI reference to the symbol to use.
func (e *SVGUSEElement) HREF(s string) *SVGUSEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("href", s)
	return e
}

func (e *SVGUSEElement) IfHREF(condition bool, s string) *SVGUSEElement {
	if condition {
		e.HREF(s)
	}
	return e
}

// Remove the attribute href from the element.
func (e *SVGUSEElement) HREFRemove(s string) *SVGUSEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("href")
	return e
}

// The x-axis coordinate of the side of the rectangular region which is closest to
// the user.
func (e *SVGUSEElement) X(f float64) *SVGUSEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("x", f)
	return e
}

func (e *SVGUSEElement) IfX(condition bool, f float64) *SVGUSEElement {
	if condition {
		e.X(f)
	}
	return e
}

// The y-axis coordinate of the side of the rectangular region which is closest to
// the user.
func (e *SVGUSEElement) Y(f float64) *SVGUSEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("y", f)
	return e
}

func (e *SVGUSEElement) IfY(condition bool, f float64) *SVGUSEElement {
	if condition {
		e.Y(f)
	}
	return e
}

// The width of the rectangular region.
func (e *SVGUSEElement) WIDTH(f float64) *SVGUSEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("width", f)
	return e
}

func (e *SVGUSEElement) IfWIDTH(condition bool, f float64) *SVGUSEElement {
	if condition {
		e.WIDTH(f)
	}
	return e
}

// The height of the rectangular region.
func (e *SVGUSEElement) HEIGHT(f float64) *SVGUSEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("height", f)
	return e
}

func (e *SVGUSEElement) IfHEIGHT(condition bool, f float64) *SVGUSEElement {
	if condition {
		e.HEIGHT(f)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGUSEElement) CLASS(s ...string) *SVGUSEElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

func (e *SVGUSEElement) IfCLASS(condition bool, s ...string) *SVGUSEElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Remove the attribute class from the element.
func (e *SVGUSEElement) CLASSRemove(s ...string) *SVGUSEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies a unique id for an element
func (e *SVGUSEElement) ID(s string) *SVGUSEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

func (e *SVGUSEElement) IfID(condition bool, s string) *SVGUSEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Remove the attribute id from the element.
func (e *SVGUSEElement) IDRemove(s string) *SVGUSEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGUSEElement) STYLEF(k string, format string, args ...any) *SVGUSEElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

func (e *SVGUSEElement) IfSTYLE(condition bool, k string, v string) *SVGUSEElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

func (e *SVGUSEElement) STYLE(k string, v string) *SVGUSEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

func (e *SVGUSEElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGUSEElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Add the attributes in the map to the element.
func (e *SVGUSEElement) STYLEMap(m map[string]string) *SVGUSEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Add pairs of attributes to the element.
func (e *SVGUSEElement) STYLEPairs(pairs ...string) *SVGUSEElement {
	if len(pairs)%2 != 0 {
		panic("Must have an even number of pairs")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}

	for i := 0; i < len(pairs); i += 2 {
		kv.Add(pairs[i], pairs[i+1])
	}

	return e
}

func (e *SVGUSEElement) IfSTYLEPairs(condition bool, pairs ...string) *SVGUSEElement {
	if condition {
		e.STYLEPairs(pairs...)
	}
	return e
}

// Remove the attribute style from the element.
func (e *SVGUSEElement) STYLERemove(keys ...string) *SVGUSEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
