// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package svg is generated from configuration file.
// Description:
// Scalable Vector Graphics (SVG) is an XML-based markup language for describing 
// two-dimensional based vector graphics 
// As such, it's a text-based, open Web standard for describing images that can be 
// rendered cleanly at any size and are designed specifically to work well with 
// other web standards including CSS, DOM, JavaScript, and SMIL 
// SVG is, essentially, to graphics what HTML is to text 
// SVG images and their related behaviors are defined in XML text files, which 
// means they can be searched, indexed, scripted, and compressed 
// Additionally, this means they can be created and edited with any text editor or 
// with drawing software 
// Compared to classic bitmapped image formats such as JPEG or PNG, SVG-format 
// vector images can be rendered at any size without loss of quality and can be 
// easily localized by updating the text within them, without the need of a 
// graphical editor to do so 
// With proper libraries, SVG files can even be localized on-the-fly. 
package svg

import(
    "fmt"
    "github.com/igrmk/treemap/v2"
)

// The <feComposite> SVG filter primitive performs the combination of two input 
// images pixel-wise in image space using one of the Porter-Duff compositing 
// operations: over, in, atop, out, xor. 
type FECOMPOSITEElementBuilder struct {
    *ElementBuilder
}

// Create a new FECOMPOSITEElementBuilder element.
// This will create a new element with the tag
// "feComposite" during rendering.
func FECOMPOSITE(children ...ElementRenderer) *FECOMPOSITEElementBuilder {
    return &FECOMPOSITEElementBuilder{
        ElementBuilder: &ElementBuilder{
            Tag: []byte("feComposite"),
            IsSelfClosing: false,
            Descendants: children,
		},
    }
}

func (e *FECOMPOSITEElementBuilder) Children(children ...ElementRenderer) *FECOMPOSITEElementBuilder {
    e.Descendants = append(e.Descendants, children...)
    return e
}

func(e *FECOMPOSITEElementBuilder) IfChildren(condition bool, children ...ElementRenderer) *FECOMPOSITEElementBuilder {
    if condition {
        e.Descendants = append(e.Descendants, children...)
    }
    return e
}

func(e *FECOMPOSITEElementBuilder) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *FECOMPOSITEElementBuilder {
    if condition {
        e.Descendants = append(e.Descendants, trueChildren)
    } else {
        e.Descendants = append(e.Descendants, falseChildren)
    }
    return e
}

func (e *FECOMPOSITEElementBuilder) Text(text string) *FECOMPOSITEElementBuilder {
    e.Descendants = append(e.Descendants, Text(text))
    return e
}

func (e *FECOMPOSITEElementBuilder) TextF(format string, args ...any) *FECOMPOSITEElementBuilder {
    return e.Text(fmt.Sprintf(format, args...))
}

func (e *FECOMPOSITEElementBuilder) Escaped(text string) *FECOMPOSITEElementBuilder {
    e.Descendants = append(e.Descendants, Escaped(text))
    return e
}

func (e *FECOMPOSITEElementBuilder) EscapedF(format string, args ...any) *FECOMPOSITEElementBuilder {
    return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *FECOMPOSITEElementBuilder) CustomData(key, value string) *FECOMPOSITEElementBuilder {
    if e.CustomDataAttributes == nil {
        e.CustomDataAttributes = treemap.New[string,string]()
    }
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *FECOMPOSITEElementBuilder) CustomDataRemove(key string) *FECOMPOSITEElementBuilder {
	if e.CustomDataAttributes == nil {
		return e
	}
    e.CustomDataAttributes.Del(key)
	return e
}


// Input for the compositing operation. 
func(e *FECOMPOSITEElementBuilder) IN(s string) *FECOMPOSITEElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("in", s)
    return e
}

// Remove the attribute in from the element.
func(e *FECOMPOSITEElementBuilder) INRemove(s string) *FECOMPOSITEElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("in")
    return e
}


// Second input for the compositing operation. 
func(e *FECOMPOSITEElementBuilder) IN2(s string) *FECOMPOSITEElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("in2", s)
    return e
}

// Remove the attribute in2 from the element.
func(e *FECOMPOSITEElementBuilder) IN2Remove(s string) *FECOMPOSITEElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("in2")
    return e
}


// The type of compositing operation. 
func(e *FECOMPOSITEElementBuilder) OPERATOR(c FeCompositeOperatorChoice) *FECOMPOSITEElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("operator", string(c))
    return e
}

type FeCompositeOperatorChoice string
const(
// The source image is composited over the destination image. 
    FeCompositeOperator_over FeCompositeOperatorChoice = "over"
// The part of the source image that lies inside of the destination image is 
// composited over the destination image. 
    FeCompositeOperator_in FeCompositeOperatorChoice = "in"
// The part of the source image that lies outside of the destination image is 
// composited over the destination image. 
    FeCompositeOperator_out FeCompositeOperatorChoice = "out"
// The part of the source image that lies inside of the destination image is 
// composited over the destination image and replaces the destination image. 
    FeCompositeOperator_atop FeCompositeOperatorChoice = "atop"
// The part of the source image that lies outside of the destination image is 
// composited over the destination image. 
    FeCompositeOperator_xor FeCompositeOperatorChoice = "xor"
// A standard arithmetic operator is applied ( 
    FeCompositeOperator_arithmetic FeCompositeOperatorChoice = "arithmetic"
)

// Remove the attribute operator from the element.
func(e *FECOMPOSITEElementBuilder) OPERATORRemove(c FeCompositeOperatorChoice) *FECOMPOSITEElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("operator")
    return e
}


// First value to use in the arithmetic operation. 
func(e *FECOMPOSITEElementBuilder) K1(f float64) *FECOMPOSITEElementBuilder{
    if e.FloatAttributes == nil {
        e.FloatAttributes = treemap.New[string,float64]()
    }
    e.FloatAttributes.Set("k1", f)
    return e
}



// Second value to use in the arithmetic operation. 
func(e *FECOMPOSITEElementBuilder) K2(f float64) *FECOMPOSITEElementBuilder{
    if e.FloatAttributes == nil {
        e.FloatAttributes = treemap.New[string,float64]()
    }
    e.FloatAttributes.Set("k2", f)
    return e
}



// Third value to use in the arithmetic operation. 
func(e *FECOMPOSITEElementBuilder) K3(f float64) *FECOMPOSITEElementBuilder{
    if e.FloatAttributes == nil {
        e.FloatAttributes = treemap.New[string,float64]()
    }
    e.FloatAttributes.Set("k3", f)
    return e
}



// Fourth value to use in the arithmetic operation. 
func(e *FECOMPOSITEElementBuilder) K4(f float64) *FECOMPOSITEElementBuilder{
    if e.FloatAttributes == nil {
        e.FloatAttributes = treemap.New[string,float64]()
    }
    e.FloatAttributes.Set("k4", f)
    return e
}



// Specifies one or more classnames for an element (refers to a class in a style 
// sheet) 
func(e *FECOMPOSITEElementBuilder) CLASS(s ...string) *FECOMPOSITEElementBuilder{
    if e.DelimitedStrings == nil {
        e.DelimitedStrings = treemap.New[string,*DelimitedBuilder[string]]()
    }
    ds, ok := e.DelimitedStrings.Get("class")
    if !ok {
        ds = NewDelimitedBuilder[string](" ")
        e.DelimitedStrings.Set("class", ds)
    }
    ds.Add(s...)
    return e
}

// Remove the attribute class from the element.
func(e *FECOMPOSITEElementBuilder) CLASSRemove(s ...string) *FECOMPOSITEElementBuilder{
    if e.DelimitedStrings == nil {
        return e
    }
    ds, ok := e.DelimitedStrings.Get("class")
    if !ok {
        return e
    }
    ds.Remove(s ...)
    return e
}



// Specifies a unique id for an element 
func(e *FECOMPOSITEElementBuilder) ID(s string) *FECOMPOSITEElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("id", s)
    return e
}

// Remove the attribute id from the element.
func(e *FECOMPOSITEElementBuilder) IDRemove(s string) *FECOMPOSITEElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("id")
    return e
}


// Specifies an inline CSS style for an element 
func (e *FECOMPOSITEElementBuilder) STYLE(k string, v string) *FECOMPOSITEElementBuilder {
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }
    kv.Add(k, v)
    return e
}

// Add the attributes in the map to the element.
func (e *FECOMPOSITEElementBuilder) STYLEMap(m map[string]string) *FECOMPOSITEElementBuilder {
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }
    for k, v := range m {
        kv.Add(k, v)
    }
    return e
}

// Add pairs of attributes to the element.
func (e *FECOMPOSITEElementBuilder) STYLEPairs(pairs ...string) *FECOMPOSITEElementBuilder {
    if len(pairs) % 2 != 0 {
        panic("Must have an even number of pairs")
    }
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }

    for i := 0; i < len(pairs); i += 2 {
        kv.Add(pairs[i], pairs[i+1])
    }

    return e
}


// Remove the attribute style from the element.
func (e *FECOMPOSITEElementBuilder) STYLERemove(keys ...string) *FECOMPOSITEElementBuilder {
    if e.KVStrings == nil {
        return e
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        return e
    }
    for _, k := range keys {
        kv.Remove(k)
    }
    return e
}



