// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package svg is generated from configuration file.
// Description:
// Scalable Vector Graphics (SVG) is an XML-based markup language for describing 
// two-dimensional based vector graphics 
// As such, it's a text-based, open Web standard for describing images that can be 
// rendered cleanly at any size and are designed specifically to work well with 
// other web standards including CSS, DOM, JavaScript, and SMIL 
// SVG is, essentially, to graphics what HTML is to text 
// SVG images and their related behaviors are defined in XML text files, which 
// means they can be searched, indexed, scripted, and compressed 
// Additionally, this means they can be created and edited with any text editor or 
// with drawing software 
// Compared to classic bitmapped image formats such as JPEG or PNG, SVG-format 
// vector images can be rendered at any size without loss of quality and can be 
// easily localized by updating the text within them, without the need of a 
// graphical editor to do so 
// With proper libraries, SVG files can even be localized on-the-fly. 
package svg

import(
    "fmt"
    "github.com/igrmk/treemap/v2"
)

// The <script> SVG element includes scripts, which can be used to trigger user 
// interface events. 
type SCRIPTElementBuilder struct {
    *ElementBuilder
}

// Create a new SCRIPTElementBuilder element.
// This will create a new element with the tag
// "script" during rendering.
func SCRIPT(children ...ElementRenderer) *SCRIPTElementBuilder {
    return &SCRIPTElementBuilder{
        ElementBuilder: &ElementBuilder{
            Tag: []byte("script"),
            IsSelfClosing: false,
            Descendants: children,
		},
    }
}

func (e *SCRIPTElementBuilder) Children(children ...ElementRenderer) *SCRIPTElementBuilder {
    e.Descendants = append(e.Descendants, children...)
    return e
}

func(e *SCRIPTElementBuilder) IfChildren(condition bool, children ...ElementRenderer) *SCRIPTElementBuilder {
    if condition {
        e.Descendants = append(e.Descendants, children...)
    }
    return e
}

func(e *SCRIPTElementBuilder) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SCRIPTElementBuilder {
    if condition {
        e.Descendants = append(e.Descendants, trueChildren)
    } else {
        e.Descendants = append(e.Descendants, falseChildren)
    }
    return e
}

func (e *SCRIPTElementBuilder) Text(text string) *SCRIPTElementBuilder {
    e.Descendants = append(e.Descendants, Text(text))
    return e
}

func (e *SCRIPTElementBuilder) TextF(format string, args ...any) *SCRIPTElementBuilder {
    return e.Text(fmt.Sprintf(format, args...))
}

func (e *SCRIPTElementBuilder) Escaped(text string) *SCRIPTElementBuilder {
    e.Descendants = append(e.Descendants, Escaped(text))
    return e
}

func (e *SCRIPTElementBuilder) EscapedF(format string, args ...any) *SCRIPTElementBuilder {
    return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SCRIPTElementBuilder) CustomData(key, value string) *SCRIPTElementBuilder {
    if e.CustomDataAttributes == nil {
        e.CustomDataAttributes = treemap.New[string,string]()
    }
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SCRIPTElementBuilder) CustomDataRemove(key string) *SCRIPTElementBuilder {
	if e.CustomDataAttributes == nil {
		return e
	}
    e.CustomDataAttributes.Del(key)
	return e
}


// The scripting language used for the given script element. 
func(e *SCRIPTElementBuilder) TYPE(s string) *SCRIPTElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("type", s)
    return e
}

// Remove the attribute type from the element.
func(e *SCRIPTElementBuilder) TYPERemove(s string) *SCRIPTElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("type")
    return e
}


// A Uniform Resource Identifier (URI) reference that specifies the location of 
// the script to execute. 
func(e *SCRIPTElementBuilder) HREF(s string) *SCRIPTElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("href", s)
    return e
}

// Remove the attribute href from the element.
func(e *SCRIPTElementBuilder) HREFRemove(s string) *SCRIPTElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("href")
    return e
}


// How the element handles crossorigin requests. 
func(e *SCRIPTElementBuilder) CROSSORIGIN(c ScriptCrossoriginChoice) *SCRIPTElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("crossorigin", string(c))
    return e
}

type ScriptCrossoriginChoice string
const(
// How the element handles crossorigin requests. 
    ScriptCrossorigin_anonymous ScriptCrossoriginChoice = "anonymous"
// How the element handles crossorigin requests. 
    ScriptCrossorigin_use_credentials ScriptCrossoriginChoice = "use-credentials"
)

// Remove the attribute crossorigin from the element.
func(e *SCRIPTElementBuilder) CROSSORIGINRemove(c ScriptCrossoriginChoice) *SCRIPTElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("crossorigin")
    return e
}


// Specifies one or more classnames for an element (refers to a class in a style 
// sheet) 
func(e *SCRIPTElementBuilder) CLASS(s ...string) *SCRIPTElementBuilder{
    if e.DelimitedStrings == nil {
        e.DelimitedStrings = treemap.New[string,*DelimitedBuilder[string]]()
    }
    ds, ok := e.DelimitedStrings.Get("class")
    if !ok {
        ds = NewDelimitedBuilder[string](" ")
        e.DelimitedStrings.Set("class", ds)
    }
    ds.Add(s...)
    return e
}

// Remove the attribute class from the element.
func(e *SCRIPTElementBuilder) CLASSRemove(s ...string) *SCRIPTElementBuilder{
    if e.DelimitedStrings == nil {
        return e
    }
    ds, ok := e.DelimitedStrings.Get("class")
    if !ok {
        return e
    }
    ds.Remove(s ...)
    return e
}



// Specifies a unique id for an element 
func(e *SCRIPTElementBuilder) ID(s string) *SCRIPTElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("id", s)
    return e
}

// Remove the attribute id from the element.
func(e *SCRIPTElementBuilder) IDRemove(s string) *SCRIPTElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("id")
    return e
}


// Specifies an inline CSS style for an element 
func (e *SCRIPTElementBuilder) STYLE(k string, v string) *SCRIPTElementBuilder {
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }
    kv.Add(k, v)
    return e
}

// Add the attributes in the map to the element.
func (e *SCRIPTElementBuilder) STYLEMap(m map[string]string) *SCRIPTElementBuilder {
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }
    for k, v := range m {
        kv.Add(k, v)
    }
    return e
}

// Add pairs of attributes to the element.
func (e *SCRIPTElementBuilder) STYLEPairs(pairs ...string) *SCRIPTElementBuilder {
    if len(pairs) % 2 != 0 {
        panic("Must have an even number of pairs")
    }
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }

    for i := 0; i < len(pairs); i += 2 {
        kv.Add(pairs[i], pairs[i+1])
    }

    return e
}


// Remove the attribute style from the element.
func (e *SCRIPTElementBuilder) STYLERemove(keys ...string) *SCRIPTElementBuilder {
    if e.KVStrings == nil {
        return e
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        return e
    }
    for _, k := range keys {
        kv.Remove(k)
    }
    return e
}



