// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package svg is generated from configuration file.
// Description:
// Scalable Vector Graphics (SVG) is an XML-based markup language for describing 
// two-dimensional based vector graphics 
// As such, it's a text-based, open Web standard for describing images that can be 
// rendered cleanly at any size and are designed specifically to work well with 
// other web standards including CSS, DOM, JavaScript, and SMIL 
// SVG is, essentially, to graphics what HTML is to text 
// SVG images and their related behaviors are defined in XML text files, which 
// means they can be searched, indexed, scripted, and compressed 
// Additionally, this means they can be created and edited with any text editor or 
// with drawing software 
// Compared to classic bitmapped image formats such as JPEG or PNG, SVG-format 
// vector images can be rendered at any size without loss of quality and can be 
// easily localized by updating the text within them, without the need of a 
// graphical editor to do so 
// With proper libraries, SVG files can even be localized on-the-fly. 
package svg

import(
    "fmt"
    "github.com/igrmk/treemap/v2"
)

// The <style> SVG element allows style sheets to be embedded directly within SVG 
// content 
// SVG's style element has the same attributes as the corresponding element in 
// HTML (see HTML's <style> element). 
type STYLEElementBuilder struct {
    *ElementBuilder
}

// Create a new STYLEElementBuilder element.
// This will create a new element with the tag
// "style" during rendering.
func STYLE(children ...ElementRenderer) *STYLEElementBuilder {
    return &STYLEElementBuilder{
        ElementBuilder: &ElementBuilder{
            Tag: []byte("style"),
            IsSelfClosing: false,
            Descendants: children,
		},
    }
}

func (e *STYLEElementBuilder) Children(children ...ElementRenderer) *STYLEElementBuilder {
    e.Descendants = append(e.Descendants, children...)
    return e
}

func(e *STYLEElementBuilder) IfChildren(condition bool, children ...ElementRenderer) *STYLEElementBuilder {
    if condition {
        e.Descendants = append(e.Descendants, children...)
    }
    return e
}

func(e *STYLEElementBuilder) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *STYLEElementBuilder {
    if condition {
        e.Descendants = append(e.Descendants, trueChildren)
    } else {
        e.Descendants = append(e.Descendants, falseChildren)
    }
    return e
}

func (e *STYLEElementBuilder) Text(text string) *STYLEElementBuilder {
    e.Descendants = append(e.Descendants, Text(text))
    return e
}

func (e *STYLEElementBuilder) TextF(format string, args ...any) *STYLEElementBuilder {
    return e.Text(fmt.Sprintf(format, args...))
}

func (e *STYLEElementBuilder) Escaped(text string) *STYLEElementBuilder {
    e.Descendants = append(e.Descendants, Escaped(text))
    return e
}

func (e *STYLEElementBuilder) EscapedF(format string, args ...any) *STYLEElementBuilder {
    return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *STYLEElementBuilder) CustomData(key, value string) *STYLEElementBuilder {
    if e.CustomDataAttributes == nil {
        e.CustomDataAttributes = treemap.New[string,string]()
    }
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *STYLEElementBuilder) CustomDataRemove(key string) *STYLEElementBuilder {
	if e.CustomDataAttributes == nil {
		return e
	}
    e.CustomDataAttributes.Del(key)
	return e
}


// The style sheet language. 
func(e *STYLEElementBuilder) TYPE(s string) *STYLEElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("type", s)
    return e
}

// Remove the attribute type from the element.
func(e *STYLEElementBuilder) TYPERemove(s string) *STYLEElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("type")
    return e
}


// The intended destination medium for style information. 
func(e *STYLEElementBuilder) MEDIA(s string) *STYLEElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("media", s)
    return e
}

// Remove the attribute media from the element.
func(e *STYLEElementBuilder) MEDIARemove(s string) *STYLEElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("media")
    return e
}


// The advisory title. 
func(e *STYLEElementBuilder) TITLE(s string) *STYLEElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("title", s)
    return e
}

// Remove the attribute title from the element.
func(e *STYLEElementBuilder) TITLERemove(s string) *STYLEElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("title")
    return e
}


// Specifies one or more classnames for an element (refers to a class in a style 
// sheet) 
func(e *STYLEElementBuilder) CLASS(s ...string) *STYLEElementBuilder{
    if e.DelimitedStrings == nil {
        e.DelimitedStrings = treemap.New[string,*DelimitedBuilder[string]]()
    }
    ds, ok := e.DelimitedStrings.Get("class")
    if !ok {
        ds = NewDelimitedBuilder[string](" ")
        e.DelimitedStrings.Set("class", ds)
    }
    ds.Add(s...)
    return e
}

// Remove the attribute class from the element.
func(e *STYLEElementBuilder) CLASSRemove(s ...string) *STYLEElementBuilder{
    if e.DelimitedStrings == nil {
        return e
    }
    ds, ok := e.DelimitedStrings.Get("class")
    if !ok {
        return e
    }
    ds.Remove(s ...)
    return e
}



// Specifies a unique id for an element 
func(e *STYLEElementBuilder) ID(s string) *STYLEElementBuilder{
    if e.StringAttributes == nil {
        e.StringAttributes = treemap.New[string,string]()
    }
    e.StringAttributes.Set("id", s)
    return e
}

// Remove the attribute id from the element.
func(e *STYLEElementBuilder) IDRemove(s string) *STYLEElementBuilder{
    if e.StringAttributes == nil {
        return e
    }
    e.StringAttributes.Del("id")
    return e
}


// Specifies an inline CSS style for an element 
func (e *STYLEElementBuilder) STYLE(k string, v string) *STYLEElementBuilder {
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }
    kv.Add(k, v)
    return e
}

// Add the attributes in the map to the element.
func (e *STYLEElementBuilder) STYLEMap(m map[string]string) *STYLEElementBuilder {
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }
    for k, v := range m {
        kv.Add(k, v)
    }
    return e
}

// Add pairs of attributes to the element.
func (e *STYLEElementBuilder) STYLEPairs(pairs ...string) *STYLEElementBuilder {
    if len(pairs) % 2 != 0 {
        panic("Must have an even number of pairs")
    }
    if e.KVStrings == nil {
        e.KVStrings = treemap.New[string,*KVBuilder]()
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        kv = NewKVBuilder(":", ";")
        e.KVStrings.Set("style", kv)
    }

    for i := 0; i < len(pairs); i += 2 {
        kv.Add(pairs[i], pairs[i+1])
    }

    return e
}


// Remove the attribute style from the element.
func (e *STYLEElementBuilder) STYLERemove(keys ...string) *STYLEElementBuilder {
    if e.KVStrings == nil {
        return e
    }
    kv, ok := e.KVStrings.Get("style")
    if !ok {
        return e
    }
    for _, k := range keys {
        kv.Remove(k)
    }
    return e
}



